name: Teste de qualidade
run-name: ${{ github.actor }}
on: [push]
jobs:
  teste_qualidade:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Do Projeto
          uses: actions/checkout@v2
        - name: Instalação do flake8
          run: pip install flake8
        - name: Run Teste ignorando o import no topo
          run: flake8 --ignore=F401 || exit 1
